folder_train: /content/drive/My Drive/mice_data/Train
folder_validate: /content/drive/My Drive/mice_data/Validate

image_shape:
 - 128
 - 128
 - 64

mice:
 - 1
 - 5
 - 9
 - 59
 - 63
 - 67
 - 71
 - 75
 - 2
 - 6
 - 10
 - 56
 - 60
 - 64
 - 72
 - 76
 - 3
 - 7
 - 11
 - 57
 - 61
 - 65
 - 69
 - 77
 - 4
 - 8
 - 12
 - 58
 - 62
 - 73
 - 74
 - 78


tumor_type:
 CD44 WT:
  - 1
  - 5
  - 9
  - 59
  - 63
  - 67
  - 71
  - 75
  - 2
  - 6
  - 10
  - 56
  - 60
  - 64
  - 72
  - 76

 CD44 siRNA:
  - 3
  - 7
  - 11
  - 57
  - 61
  - 65
  - 69
  - 77
  - 4
  - 8
  - 12
  - 58
  - 62
  - 73
  - 74
  - 78

irradiation:
 control:
  - 1
  - 5
  - 9
  - 59
  - 63
  - 67
  - 71
  - 75
  - 3
  - 7
  - 11
  - 57
  - 61
  - 65
  - 69
  - 77

 irradiated:
  - 2
  - 6
  - 10
  - 56
  - 60
  - 64
  - 72
  - 76
  - 4
  - 8
  - 12
  - 58
  - 62
  - 73
  - 74
  - 78

